### PR TITLE
Now allowing to declare the maximum connections count of plugs and sockets

### PR DESCRIPTION
**Pull request by glm-ypinczon**
(use -1 for infinite)
Also added attributes in the sample that work the opposite way than default: plugs accepts only 1 connection and sockets accepts infinite connections 

Resolves Issue #20

### CODE REVIEW

**Comment by glm-ypinczon** [comment]
Actually both 0 or -1 will mean that an infinite connections count is allowed ;)

**Comment by LeGoffLoic** [comment]
Can you add your changes to the README.md and include it in your PR ? 
Will test and merge after work.

Thx

**Comment by LeGoffLoic** [comment]
Also, it would be nice to change the editAttribute() so we can change the plug/socketMaxConnections. Let me know if you want to add that to your PR, then I will wait to merge.

**Comment by glm-ypinczon** [comment]
I just fixed the missing updates on the readme file, but I won't do the editAttribute (yet) as I miss a bit of time ;)
You can merge this one as is, I'll open a new one if I do the edit attribute.

**Pull request merged**
