### PR TITLE
Dev auto layout graph

### PR DESCRIPTION
**Pull request by glm-ypinczon**
Added an autoLayoutGraph method that will layout the given nodes in the graph automatically

Added in readme
Added in nodz_demo (l key)

Could be greatly improved, but already does the job.

### CODE REVIEW

**Comment by coderbone** [comment]
interesting, I tackled this problem by running a 'dot' subprocess to do graph layout... I should have used pydot but I already had a home rolled dot driver laying about from previous experimentation

**Comment by glm-ypinczon** [comment]
I'm mainly a c++ developer, not python, so I don't know all good python libraries yet. Is there a way to do this with the basic pytons libs ?
I would gladly change this by something more standard if already available.

**Comment by coderbone** [comment]
I'm a C++ guy trapped in a python world :), pydot is probably the way to go for powerful layout algorithms
but will introduce a dependency that may be a bridge too far for some potential users, I like the fact that
Nodz is pure Qt... as a C++ guy you may want to check out the graphviz library if you ever need to do layouts from that language

From the looks of it your layout code is going to give a lot of people value, even something fairly simple is going to be enough for most.

**Comment by morganloomis** [comment]
Personally I'd appreciate minimal dependencies, what I love about this project is how light weight it is.

**Comment by LeGoffLoic** [comment]
I will take a look but If implemented as part of Nodz, I will try to
implement with no external dependencies.
But I am not sure if this should be part of nodz. I think it's more of a
feature that would live on a main UI/tool wrapped around Nodz.
(Why ?)
Because every user might want to layout the nodes differently. Nodz is only
providing nodes without data. Anything that you want to do with them (other
than connections) shouldn't be part of Nodz.

That's my point of view and it's also a way to keep things light weight and
simple.

Let me know what you think about it.

Cheers

**Comment by LeGoffLoic** [comment]
@glm-ypinczon , I like your approach as it doesn't have any dependency. That's something I wanted to implement in my version 2.0. Will probably keep it and add it with the next big feature.

**Comment by glm-ypinczon** [comment]
oK
Should I remove it form the main and add it in nodz_utils instead, or will you take parts of what you need anyway and do it on your own ?

**Comment by pleprince** [comment]
I think it's good to have basic graph layout out of the box. I had to implement it too.
Graph layout is a very complex issue and this simple implementation is definitely valuable.

**Comment by LeGoffLoic** [comment]
@glm-ypinczon Leave it for now. I will implement it directly in nodz_main this weekend. Will take a look at your code and see if optimizations are needed or if I can add it as it is.

**Pull request closed without merging**
